services:
  docscan:
    image: ghcr.io/nurlanomarov/docscan:latest
    container_name: docscan
    restart: always
    ports:
      - "3007:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - labai-network

networks:
  labai-network:
    external: true
    name: labai_labai-network
